format:
  gradle:
    id: io.spring.javaformat
    version: 0.0.43
    default-task: format
    description: Formats source code
    tasks:
      format: format
    repository: gradlePluginPortal()
  maven:
    id: io.spring.javaformat:spring-javaformat-maven-plugin
    version: 0.0.43
    default-task: apply
    description: Formats source code
    tasks:
      apply: :apply
rockcraft:
  resources:
    - path: .config/config.xml
      content: |
        <resource/>
  gradle:
    id: io.github.rockcrafters.rockcraft
    version: 1.2.3
    repository: gradlePluginPortal()
    default-task: build-rock
    description: |
      Plugin for rock image generation
    tasks:
      create-rock:
        - create-rock
      build-rock: build-rock
      create-build-rock: create-build-rock
      build-build-rock: build-build-rock
      push-rock: push-rock
      push-build-rock: push-build-rock
    configuration:
      maven:
          configuration: |
            <maven-element-config/>
          dependencies: |
            <dependencies/>
          executions: | 
            <executions/>
      gradleKotlin: |
        configure<com.canonical.rockcraft.builder.RockcraftOptions> {
            setTargetRelease(21)
        }
      gradleGroovy: |
        groovyDslObject {
        }
  maven:
    id: io.github.rockcrafters:rockcraft-maven-plugin
    version: 1.2.3
    default-task: build-rock
    description: |
      Plugin for rock image generation
    tasks:
      create-rock:
        - install
        - :create-rock
      build-rock:
        - install
        - :create-rock
        - :build-rock
      create-build-rock:
        - install
        - :create-build-rock
      push-rock:
        - install
        - :create-rock
        - :build-rock
        - :push-rock
